package com.example.geoquizfrontend;

public class CountryNames {
    public static String[] countries = {
            "Uzbekistan",
            "Austria",
            "Sierra Leone",
            "Cocos (Keeling) Islands",
            "Mauritania",
            "Israel",
            "Moldova",
            "Fiji",
            "Serbia",
            "Cameroon",
            "Bahamas",
            "Nauru",
            "Czechia",
            "Egypt",
            "Myanmar",
            "Netherlands",
            "Uruguay",
            "Northern Mariana Islands",
            "Central African Republic",
            "Saint Helena, Ascension and Tristan da Cunha",
            "Equatorial Guinea",
            "Colombia",
            "Kyrgyzstan",
            "Spain",
            "Malawi",
            "Hungary",
            "Monaco",
            "Cape Verde",
            "South Africa",
            "Denmark",
            "Guadeloupe",
            "Ireland",
            "Malta",
            "Wallis and Futuna",
            "Suriname",
            "Vatican City",
            "Mali",
            "Tonga",
            "San Marino",
            "Saint Barthélemy",
            "Gibraltar",
            "Canada",
            "Benin",
            "Guam",
            "North Korea",
            "Tuvalu",
            "Panama",
            "Rwanda",
            "Republic of the Congo",
            "Jamaica",
            "Bahrain",
            "Sint Maarten",
            "Turks and Caicos Islands",
            "Pakistan",
            "Kazakhstan",
            "Laos",
            "Trinidad and Tobago",
            "Montenegro",
            "Niue",
            "Liberia",
            "Grenada",
            "Papua New Guinea",
            "Chad",
            "Chile",
            "Puerto Rico",
            "Saudi Arabia",
            "Norway",
            "Gambia",
            "Philippines",
            "Isle of Man",
            "Portugal",
            "Honduras",
            "Cyprus",
            "Anguilla",
            "Heard Island and McDonald Islands",
            "Togo",
            "Lebanon",
            "Morocco",
            "Estonia",
            "Faroe Islands",
            "Argentina",
            "Gabon",
            "Namibia",
            "Vietnam",
            "Greece",
            "British Virgin Islands",
            "Mozambique",
            "Norfolk Island",
            "South Georgia",
            "Armenia",
            "Kenya",
            "Bhutan",
            "United Arab Emirates",
            "Cook Islands",
            "Ethiopia",
            "Singapore",
            "Peru",
            "Palestine",
            "Samoa",
            "South Sudan",
            "Andorra",
            "Saint Martin",
            "Eswatini",
            "Tajikistan",
            "Zambia",
            "United States",
            "Burundi",
            "Japan",
            "Curaçao",
            "Uganda",
            "Mongolia",
            "Nigeria",
            "Guatemala",
            "Jersey",
            "Costa Rica",
            "Yemen",
            "Greenland",
            "Madagascar",
            "Algeria",
            "Belgium",
            "Sri Lanka",
            "Finland",
            "Bermuda",
            "North Macedonia",
            "Saint Vincent and the Grenadines",
            "Niger",
            "British Indian Ocean Territory",
            "Latvia",
            "Nepal",
            "Ivory Coast",
            "Liechtenstein",
            "DR Congo",
            "Belize",
            "Qatar",
            "Tokelau",
            "Indonesia",
            "French Polynesia",
            "Lesotho",
            "Poland",
            "Palau",
            "Guernsey",
            "Antigua and Barbuda",
            "Saint Pierre and Miquelon",
            "Kosovo",
            "Western Sahara",
            "Luxembourg",
            "Taiwan",
            "Hong Kong",
            "Turkmenistan",
            "Russia",
            "Azerbaijan",
            "Ecuador",
            "Cambodia",
            "Mayotte",
            "Botswana",
            "Croatia",
            "Saint Lucia",
            "Paraguay",
            "Bolivia",
            "Maldives",
            "American Samoa",
            "Iceland",
            "Slovakia",
            "French Southern and Antarctic Lands",
            "Brunei",
            "Saint Kitts and Nevis",
            "Afghanistan",
            "Ghana",
            "Kuwait",
            "Svalbard and Jan Mayen",
            "Bangladesh",
            "Guyana",
            "Kiribati",
            "Barbados",
            "Albania",
            "Pitcairn Islands",
            "Burkina Faso",
            "Macau",
            "Seychelles",
            "Switzerland",
            "South Korea",
            "United States Virgin Islands",
            "Tunisia",
            "Bouvet Island",
            "Iran",
            "Jordan",
            "Réunion",
            "Turkey",
            "Tanzania",
            "Ukraine",
            "Mauritius",
            "Somalia",
            "Guinea",
            "French Guiana",
            "Marshall Islands",
            "Solomon Islands",
            "United States Minor Outlying Islands",
            "Lithuania",
            "Slovenia",
            "Nicaragua",
            "Dominican Republic",
            "Iraq",
            "El Salvador",
            "Venezuela",
            "Zimbabwe",
            "Sweden",
            "Thailand",
            "Timor-Leste",
            "Bosnia and Herzegovina",
            "Guinea-Bissau",
            "Montserrat",
            "Dominica",
            "Falkland Islands",
            "Caribbean Netherlands",
            "Djibouti",
            "Antarctica",
            "Haiti",
            "Comoros",
            "Italy",
            "Belarus",
            "Cayman Islands",
            "France",
            "Senegal",
            "China",
            "Sudan",
            "Oman",
            "United Kingdom",
            "Mexico",
            "Australia",
            "Cuba",
            "Eritrea",
            "Bulgaria",
            "Romania",
            "Micronesia",
            "Vanuatu",
            "Syria",
            "São Tomé and Príncipe",
            "Germany",
            "New Zealand",
            "Angola",
            "Christmas Island",
            "Aruba",
            "India",
            "Malaysia",
            "Georgia",
            "New Caledonia",
            "Libya",
            "Åland Islands",
            "Martinique",
            "Brazil"
    };

    public static String[] pngValues = {
            "https://mainfacts.com/media/images/coats_of_arms/ng.png",
            "https://mainfacts.com/media/images/coats_of_arms/tw.png",
            "https://mainfacts.com/media/images/coats_of_arms/cr.png",
            "https://mainfacts.com/media/images/coats_of_arms/bj.png",
            "https://mainfacts.com/media/images/coats_of_arms/hn.png",
            "https://mainfacts.com/media/images/coats_of_arms/pw.png",
            "https://mainfacts.com/media/images/coats_of_arms/au.png",
            "https://mainfacts.com/media/images/coats_of_arms/de.png",
            "https://mainfacts.com/media/images/coats_of_arms/uz.png",
            "https://mainfacts.com/media/images/coats_of_arms/bo.png",
            "https://mainfacts.com/media/images/coats_of_arms/ci.png",
            "https://mainfacts.com/media/images/coats_of_arms/mn.png",
            "https://mainfacts.com/media/images/coats_of_arms/sg.png",
            "https://mainfacts.com/media/images/coats_of_arms/sc.png",
            "https://mainfacts.com/media/images/coats_of_arms/ht.png",
            "https://mainfacts.com/media/images/coats_of_arms/nr.png",
            "https://mainfacts.com/media/images/coats_of_arms/pg.png",
            "https://mainfacts.com/media/images/coats_of_arms/mz.png",
            "https://mainfacts.com/media/images/coats_of_arms/pk.png",
            "https://mainfacts.com/media/images/coats_of_arms/ug.png",
            "https://mainfacts.com/media/images/coats_of_arms/aq.png",
            "https://mainfacts.com/media/images/coats_of_arms/bw.png",
            "https://mainfacts.com/media/images/coats_of_arms/it.png",
            "https://mainfacts.com/media/images/coats_of_arms/ms.png",
            "https://mainfacts.com/media/images/coats_of_arms/sa.png",
            "https://mainfacts.com/media/images/coats_of_arms/gb.png",
            "https://mainfacts.com/media/images/coats_of_arms/gt.png",
            "https://mainfacts.com/media/images/coats_of_arms/gu.png",
            "https://mainfacts.com/media/images/coats_of_arms/ao.png",
            "https://mainfacts.com/media/images/coats_of_arms/by.png",
            "https://mainfacts.com/media/images/coats_of_arms/is.png",
            "https://mainfacts.com/media/images/coats_of_arms/il.png",
            "https://mainfacts.com/media/images/coats_of_arms/lc.png",
            "https://mainfacts.com/media/images/coats_of_arms/mt.png",
            "https://mainfacts.com/media/images/coats_of_arms/om.png",
            "https://mainfacts.com/media/images/coats_of_arms/ma.png",
            "https://mainfacts.com/media/images/coats_of_arms/ck.png",
            "https://mainfacts.com/media/images/coats_of_arms/mk.png",
            "https://mainfacts.com/media/images/coats_of_arms/cd.png",
            "https://mainfacts.com/media/images/coats_of_arms/lb.png",
            "https://mainfacts.com/media/images/coats_of_arms/lr.png",
            "https://mainfacts.com/media/images/coats_of_arms/ki.png",
            "https://mainfacts.com/media/images/coats_of_arms/cy.png",
            "https://mainfacts.com/media/images/coats_of_arms/bt.png",
            "https://mainfacts.com/media/images/coats_of_arms/id.png",
            "https://mainfacts.com/media/images/coats_of_arms/ps.png",
            "https://mainfacts.com/media/images/coats_of_arms/eg.png",
            "https://mainfacts.com/media/images/coats_of_arms/xk.png",
            "https://mainfacts.com/media/images/coats_of_arms/kp.png",
            "https://mainfacts.com/media/images/coats_of_arms/iq.png",
            "https://mainfacts.com/media/images/coats_of_arms/th.png",
            "https://mainfacts.com/media/images/coats_of_arms/zw.png",
            "https://mainfacts.com/media/images/coats_of_arms/ws.png",
            "https://mainfacts.com/media/images/coats_of_arms/at.png",
            "https://mainfacts.com/media/images/coats_of_arms/tt.png",
            "https://mainfacts.com/media/images/coats_of_arms/do.png"
    };
}
